name: StockFormer
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.21.4
  - pandas=1.3.5
  - scikit-learn=1.0.1
  - statsmodels=0.13.2
  - tqdm=4.64.0
  - wrapt=1.14.1
  - xlrd=2.0.1
  - pytorch=1.9.1
  - torchvision=0.10.1
  - gym=0.21.0
  - tensorboardx=2.5
